# image compose and docs: https://hub.docker.com/_/nextcloud


version: '3.8'

services:
  nextcloud:
    image: nextcloud:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - ${APP_PORT}:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${DB_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${DB_MYSQL_NAME}
      - MYSQL_USER=${DB_MYSQL_USER}
      - MYSQL_HOST=mysql
      - NEXTCLOUD_ADMIN_USER=${APP_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${APP_PASSWORD}
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
      - NEXTCLOUD_TRUSTED_DOMAINS=
      - NEXTCLOUD_UPDATE=0
      - REDIS_HOST=redis
    depends_on: 
      - mysql
      - redis
    restart: always
    stdin_open: true
    tty: true

  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: nextcloud-mysql
    restart: always
    ports:
     - ${DB_MYSQL_PORT}:3306
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - ${VOLUMES_PATH_PREFIX}/mysql/mysql_config/conf.d:/etc/mysql/conf.d
      - ${VOLUMES_PATH_PREFIX}/mysql/mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}

  redis:
    image: redis:6
    container_name: nextcloud-redis
    restart: always
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis:/data

networks:
  default:
      name: ${APP_NETWORK}

volumes:
  nextcloud:
    driver: local
  redis:
    driver: local
  mysql:
    driver: local